"""Add OTP fields to User

Revision ID: 047b0cd807a5
Revises: 
Create Date: 2025-12-22 23:17:30.317548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047b0cd807a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'created_by')
    # ### end Alembic commands ###
