"""add notifications

Revision ID: 96b263cd59ee
Revises: a1b2c3d4e5f6
Create Date: 2026-01-09 03:02:10.677283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b263cd59ee'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint('activities_create_by_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'create_by')
    op.add_column('trips', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('device_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token')
    op.drop_column('trips', 'description')
    op.drop_column('trips', 'destination')
    op.add_column('activities', sa.Column('create_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('activities_create_by_fkey', 'activities', 'users', ['create_by'], ['id'])
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
